// Centralized image URL mapping for use across the website
// Usage: import { images } from './images'; images.Aakash, etc.

export const images = {
  Aakash: 'https://stfsl.blob.core.windows.net/fslfiles/Aakash.png',
  Akshat: 'https://stfsl.blob.core.windows.net/fslfiles/Akshat.png',
  Bharat_Pareek: 'https://stfsl.blob.core.windows.net/fslfiles/Bharat%20Pareek.jpg',
  Deepesh_Suiwal: 'https://stfsl.blob.core.windows.net/fslfiles/Deepesh%20Suiwal.png',
  Dheeraj: 'https://stfsl.blob.core.windows.net/fslfiles/Dheeraj.png',
  Hero_bg1: 'https://stfsl.blob.core.windows.net/fslfiles/Hero-bg2.jpeg',
  Hero_bg2: 'https://stfsl.blob.core.windows.net/fslfiles/Hero-bg3.jpg',
  Hero_bg3: 'https://stfsl.blob.core.windows.net/fslfiles/Hero-bg4.jpg',
  Hero_bg4: 'https://stfsl.blob.core.windows.net/fslfiles/Hero-bg5.jpeg',
  Hero_bg5: 'https://stfsl.blob.core.windows.net/fslfiles/Hero-bg6.jpeg',
  Nishita_Gupta: 'https://stfsl.blob.core.windows.net/fslfiles/Nishita%20Gupta.jpg',
  PREKSHA: 'https://stfsl.blob.core.windows.net/fslfiles/PREKSHA.png',
  Pradeep: 'https://stfsl.blob.core.windows.net/fslfiles/Pradeep.png',
  RJ: 'https://stfsl.blob.core.windows.net/fslfiles/RJ.png',
  Rajat_Jain_Nagarro: 'https://stfsl.blob.core.windows.net/fslfiles/Rajat%20Jain%20Nagarro.jpg',
  Rajat_Jain: 'https://stfsl.blob.core.windows.net/fslfiles/Rajat%20Jain.jpg',
  Ranveer_Singh: 'https://stfsl.blob.core.windows.net/fslfiles/Ranveer%20Singh.jpg',
  Rishabh_Jangir: 'https://stfsl.blob.core.windows.net/fslfiles/Rishabh%20Jangir.jpg',
  Ritik_Saluja: 'https://stfsl.blob.core.windows.net/fslfiles/Ritik%20Saluja.jpg',
  Riya_Anand: 'https://stfsl.blob.core.windows.net/fslfiles/Riya%20Anand.jpg',
  Rohit: 'https://stfsl.blob.core.windows.net/fslfiles/Rohit.png',
  RohitSir: 'https://stfsl.blob.core.windows.net/fslfiles/RohitSir.jpg',
  Suhani_Jain: 'https://stfsl.blob.core.windows.net/fslfiles/Suhani%20Jain.jpg',
  Tanmay_Shukla: 'https://stfsl.blob.core.windows.net/fslfiles/Tanmay%20Shukla.jpg',
  akshat: 'https://stfsl.blob.core.windows.net/fslfiles/akshat.jpg',
  blank: 'https://stfsl.blob.core.windows.net/fslfiles/blank.png',
  dherraj: 'https://stfsl.blob.core.windows.net/fslfiles/dherraj.jpg',
  dron: 'https://stfsl.blob.core.windows.net/fslfiles/dron.png',
  galImg1: 'https://stfsl.blob.core.windows.net/fslfiles/galImg1.jpg',
  galImg2: 'https://stfsl.blob.core.windows.net/fslfiles/galImg2.jpg',
  galImg3: 'https://stfsl.blob.core.windows.net/fslfiles/galImg3.jpg',
  galImg4: 'https://stfsl.blob.core.windows.net/fslfiles/galImg4.jpg',
  galImg5: 'https://stfsl.blob.core.windows.net/fslfiles/galImg5.jpg',
  galImg6: 'https://stfsl.blob.core.windows.net/fslfiles/galImg6.png',
  galImg7: 'https://stfsl.blob.core.windows.net/fslfiles/galImg7.jpg',
  galImg8: 'https://stfsl.blob.core.windows.net/fslfiles/galImg8.jpg',
  galImg9: 'https://stfsl.blob.core.windows.net/fslfiles/galImg9.jpg',
  gallmg8: 'https://stfsl.blob.core.windows.net/fslfiles/gallmg8.jpg',
  hero_bg: 'https://stfsl.blob.core.windows.net/fslfiles/hero-bg.jpg',
  jatin: 'https://stfsl.blob.core.windows.net/fslfiles/jatin.jpeg',
  logo: 'https://stfsl.blob.core.windows.net/fslfiles/logo.png',
  placed1: 'https://stfsl.blob.core.windows.net/fslfiles/placed1.jpg',
};