name: fsl-server-dev

on:
  workflow_dispatch:
  push:
    branches:
      - Azure-deployment
    paths:
      - 'server/**'
      - '.github/workflows/azure-deployment_fsl-server-dev.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install and build (server)
        run: |
          cd server
          npm install
          npm run build --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B9BA1DED3FDB4F65B470B9B2B0B8F4BD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AF8C0CFEA50949A8815E24F02E799637 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5D6E6F4E85AD4D77A9AA588827926ABC }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fsl-server-dev'
          slot-name: 'production'
          package: .
